name: Ghost Tile

on:
  schedule:
    - cron: '0 */2 * * 1-5' # Every 2 hours
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Random skip (50% chance)
        run: |
          # 50% chance to skip, so runs ~every 2-4 hours
          if [ $((RANDOM % 2)) -eq 0 ]; then
            echo "Skipping this run."
            exit 0
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config user.name "George Hajjar"
          git config user.email "georgehajjar99@gmail.com"

      - name: Run script
        run: bash ./bot.sh

      - name: Commit and push changes
        run: |
          git add -A
          git diff --cached --quiet || git commit -m "Automated commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
